#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JanBecaus.Droid.Resource", IsApplication=true)]

namespace JanBecaus.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int orange = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int llRoot = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int amstelgoldrace = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int beegees = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int blackeyedpeas = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ciudadjuarez = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int doscervezas = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int dowjones = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int driekwartier = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int europeanmotorshow = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int eyjafjallajokull = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int gameofshadows = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int goldenglobes = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int iowa = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int judelaw = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int kattepis = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int markwebber = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int milow = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int norahjones = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int obama = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int partofthejob = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int pussy = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int rauweblues = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int rocknroll = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int score = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int sherlockholmes = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int sighnomore = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int tomorrowland = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int tonyblair = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int usainbolt = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int vayacondios = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int wallstreet = 2130968605;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
